import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'language_change': 'Change Language',
      'english': 'English',
      'hindi': 'Hindi',
      'gujarati': 'Gujarati',
      'efficiency': 'Efficiency',
      'eff': 'Eff.',
      'picks': 'Picks',
      'avg_picks': 'A. Picks',
      'avg_speed': 'A. Speed',
      'running': 'Running',
      'stopped': "Stopped",
      'all': 'All',
      'current_stop': 'Current Stop',
      'speed': 'Speed',
      'mtrs': 'Mtrs',
      'stops': 'Stops',
      'beam_left': 'Beam Left',
      'set_picks': 'Set Picks',
      'duration': 'Duration',
      'runtime': 'Runtime',
      'oil_change_due': 'Oil Change Due',
      'greasing_due': 'Greasing Due',
      'grease_and_check_shafts': 'Grease & Check Shafts',
      'check_and_tight_nuts': 'Check & Tight Nuts',
      'machine_group': 'Machine Group',
      'machine_configure': 'Machine Configure',
      'maintenance_category': 'Maintenance Category',
      'maintenance_entry': 'Maintenance Entry',
      'shift_wise_comment_update': 'Shift wise Comment Update',
      'logout': 'Logout',
      'home': 'Home',
      'reports': 'Reports',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'live_tracking': 'Live Tracking',
      'sr_no': 'Sr. No',
      'group_name': 'Group Name',
      'enter_group_name': 'Enter Group Name',
      'machine_code': 'Machine Code',
      'machine_name': 'Machine Name',
      'udid': 'UDID',
      'efficiency_limit': 'Efficiency Limit',
      'alert': 'Alert',
      'category': 'Category',
      'type': 'Type',
      'schedule_days': 'Schedule Days',
      'alert_days': 'Alert Days',
      'alert_message': 'Alert Message',
      'active': 'Active',
      'inactive': 'Inactive',
      'Stop': 'Stop',
      'Warp': 'Warp',
      'Weft': 'Weft',
      'Feeder': 'Feeder',
      'Manual': 'Manual',
      'Other': 'Other',
      'Total': 'Total',
      'Count': 'Count',
      'Time': 'Time',
      'report_type': 'Report Type',
      'from_date': 'From Date',
      'end_date': 'End Date',
      'shift': 'Shift',
      'day_shift': 'Day Shift',
      'night_shift': 'Night Shift',
      'all_shift': 'All Shift',
      'machine': 'Machine',
      'group_wise_machine': 'Group wise Machine',
      'show_report': 'Show Report',
      'report_date': 'Date',
      'update': 'Update',
      'save': 'Save',
      'cancel': 'Cancel',
      'filter': 'Filter',
      'clear_selection': 'Clear Selection',
      'select_all': 'Select',
      'deselect_all': 'Deselect All',
    },
    'hi_IN': {
      'language_change': 'भाषा बदलें',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'gujarati': 'गुजराती',
      'efficiency': 'दक्षता',
      'eff': 'दक्षता',
      'picks': 'पिक्स',
      'avg_picks': 'औसत पिक्स',
      'avg_speed': 'औसत गति',
      'running': 'चल रहा है',
      'stopped': 'रुका हुआ',
      'all': 'सभी',
      'current_stop': 'वर्तमान स्टॉप',
      'speed': 'गति',
      'mtrs': 'मीटर',
      'stops': 'स्टॉप',
      'beam_left': 'बीम लेफ्ट',
      'set_picks': 'सेट पिक्स',
      'duration': 'अवधि',
      'runtime': 'रनटाइम',
      'oil_change_due': 'तेल बदलाव देय',
      'greasing_due': 'ग्रीसिंग देय',
      'grease_and_check_shafts': 'ग्रीस और शाफ्ट की जाँच करें',
      'check_and_tight_nuts': 'नट की जाँच और कसें',
      'machine_group': 'मशीन ग्रुप',
      'machine_configure': 'मशीन कॉन्फ़िगर करें',
      'maintenance_category': 'रखरखाव श्रेणी',
      'maintenance_entry': 'रखरखाव प्रविष्टि',
      'shift_wise_comment_update': 'शिफ्ट के अनुसार टिप्पणी अपडेट',
      'logout': 'लॉगआउट',
      'home': 'होम',
      'reports': 'रिपोर्ट',
      'notifications': 'सूचनाएं',
      'settings': 'सेटिंग्स',
      'live_tracking': 'लाइव ट्रैकिंग',
      'sr_no': 'क्रमांक',
      'group_name': 'समूह का नाम',
      'enter_group_name': 'समूह का नाम दर्ज करें',
      'machine_code': 'मशीन कोड',
      'machine_name': 'मशीन का नाम',
      'enter_machine_name': 'मशीन का नाम दर्ज करें',

      'udid': 'यूडीआईडी',
      'efficiency_limit': 'दक्षता सीमा',
      'alert': 'अलर्ट',
      'category': 'श्रेणी',
      'type': 'प्रकार',
      'schedule_days': 'शेड्यूल दिन',
      'alert_days': 'अलर्ट दिन',
      'alert_message': 'अलर्ट संदेश',
      'active': 'सक्रिय',
      'inactive': 'निष्क्रिय',
      'Stop': 'रुको',
      'Warp': 'ताना',
      'Weft': 'बाना',
      'Feeder': 'फीडर',
      'Manual': 'मैनुअल',
      'Other': 'अन्य',
      'Total': 'कुल',
      'Count': 'गिनती',
      'Time': 'समय',
      'report_type': 'रिपोर्ट प्रकार',
      'from_date': 'से तिथि',
      'end_date': 'अंतिम तिथि',
      'shift': 'शिफ्ट',
      'day_shift': 'दिन की शिफ्ट',
      'night_shift': 'रात की शिफ्ट',
      'all_shift': 'सभी शिफ्ट',
      'machine': 'मशीन',
      'group_wise_machine': 'समूह-वार मशीन',
      'show_report': 'रिपोर्ट दिखाएं',
      'report_date': 'तारीख',
      'update': 'अपडेट',
      'save': 'सेव करें',
      'cancel': 'रद्द करें',
      'filter': 'फ़िल्टर',
      'clear_selection': 'चयन साफ़ करें',
      'select_all': 'सभी चुनें',
      'deselect_all': 'सभी चयन रद्द करें',
    },
    'gu_IN': {
      'language_change': 'ભાષા બદલો',
      'english': 'અંગ્રેજી',
      'hindi': 'હિન્દી',
      'gujarati': 'ગુજરાતી',
      'efficiency': 'કાર્યક્ષમતા',
      'eff': 'કાર્યક્ષમતા',
      'picks': 'પિક્સ',
      'avg_picks': 'સરેરાશ પિક્સ',
      'avg_speed': 'સરેરાશ સ્પીડ',
      'running': 'ચાલુ',
      'stopped': 'બંધ',
      'all': 'બધા',
      'current_stop': 'હાલનો સ્ટોપ',
      'speed': 'સ્પીડ',
      'mtrs': 'મીટર',
      'stops': 'સ્ટોપ',
      'beam_left': 'બીમ બાકી',
      'set_picks': 'સેટ પિક્સ',
      'duration': 'સમયગાળો',
      'runtime': 'રનટાઇમ',
      'oil_change_due': 'ઓઇલ બદલવાનું બાકી',
      'greasing_due': 'ગ્રીસિંગ કરવાનું બાકી',
      'grease_and_check_shafts': 'શાફ્ટ પર ગ્રીસ અને ચકાસણી કરો',
      'check_and_tight_nuts': 'નટ્સ તપાસો અને સજ્જડ કરો',
      'machine_group': 'મશીન ગ્રુપ',
      'machine_configure': 'મશીન ગોઠવણી',
      'maintenance_category': 'મેન્ટેનેન્સ કેટેગરી',
      'maintenance_entry': 'મેન્ટેનેન્સ એન્ટ્રી',
      'shift_wise_comment_update': 'શિફ્ટ મુજબ ટિપ્પણી અપડેટ',
      'logout': 'લોગઆઉટ',
      'home': 'હોમ',
      'reports': 'રિપોર્ટ્સ',
      'notifications': 'જાણકારી',
      'settings': 'સેટિંગ્સ',
      'live_tracking': 'લાઈવ ટ્રેકિંગ',
      'sr_no': 'ક્રમ',
      'group_name': 'ગ્રુપનું નામ',
      'enter_group_name': 'ગ્રુપનું નામ દાખલ કરો',
      'machine_code': 'મશીન કોડ',
      'machine_name': 'મશીનનું નામ',
      'udid': 'યુડીઆઈડી',
      'efficiency_limit': 'કાર્યક્ષમતા મર્યાદા',
      'alert': 'ચેતવણી',
      'category': 'શ્રેણી',
      'type': 'પ્રકાર',
      'schedule_days': 'શેડ્યુલ દિવસો',
      'alert_days': 'ચેતવણી દિવસો',
      'alert_message': 'ચેતવણી સંદેશ',
      'active': 'સક્રિય',
      'inactive': 'નિષ્ક્રિય',
      'Warp': 'વોર્પ',
      'Weft': 'વેફ્ટ',
      'Feeder': 'ફીડર',
      'Manual': 'મેન્યુઅલ',
      'Other': 'અન્ય',
      'Total': 'કુલ',
      'Count': 'ગણતરી',
      'Time': 'સમય',
      'report_type': 'રિપોર્ટ પ્રકાર',
      'from_date': 'થી તારીખ',
      'end_date': 'અંતિમ તારીખ',
      'shift': 'શિફ્ટ',
      'day_shift': 'દિવસ પાળી',
      'night_shift': 'રાત પાળી',
      'all_shift': 'બધા શિફ્ટ',
      'machine': 'મશીન',
      'group_wise_machine': 'ગ્રુપ વાઇસ મશીન',
      'show_report': 'રિપોર્ટ બતાવો',
      'report_date': 'તારીખ',
      'update': 'અપડેટ',
      'save': 'સેવ કરો',
      'cancel': 'રદ્દ કરો',
      'filter': 'ફિલ્ટર',
      'clear_selection': 'ચયન સાફ કરો',
      'select_all': 'બધા પસંદ કરો',
      'deselect_all': 'બધા પસંદગી રદ કરો',
    },
  };
}
